# Generated by Django 3.1.4 on 2020-12-25 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_facebookpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.BigIntegerField()),
                ('text', models.TextField()),
                ('post_text', models.TextField()),
                ('shared_text', models.TextField()),
                ('time', models.DateTimeField(verbose_name='date published')),
                ('image', models.URLField()),
                ('video', models.URLField()),
                ('video_thumbnail', models.URLField()),
                ('video_id', models.BigIntegerField()),
                ('likes', models.IntegerField()),
                ('comments', models.IntegerField()),
                ('shares', models.IntegerField()),
                ('post_url', models.URLField()),
                ('link', models.URLField()),
                ('user_id', models.BigIntegerField()),
                ('images', models.URLField()),
                ('facebook_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.facebookpage')),
            ],
        ),
    ]
