# Generated by Django 3.1.4 on 2020-12-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_facebookposts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookposts',
            name='comments',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facebookposts',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facebookposts',
            name='images',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facebookposts',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facebookposts',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facebookposts',
            name='post_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facebookposts',
            name='post_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facebookposts',
            name='post_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facebookposts',
            name='shared_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facebookposts',
            name='shares',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facebookposts',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facebookposts',
            name='time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='facebookposts',
            name='user_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facebookposts',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facebookposts',
            name='video_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facebookposts',
            name='video_thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
