# Generated by Django 3.1.4 on 2020-12-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_auto_20201225_2015'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FacebookPosts',
            new_name='FacebookPost',
        ),
        migrations.AlterField(
            model_name='facebookpage',
            name='link',
            field=models.TextField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='facebookpage',
            name='name',
            field=models.TextField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='link',
            field=models.TextField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='name',
            field=models.TextField(max_length=200, unique=True),
        ),
    ]
