# Generated by Django 3.1.4 on 2020-12-31 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_auto_20201226_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookpost',
            name='manual_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
