# Generated by Django 3.1.4 on 2021-01-03 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0008_facebookpost_manual_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookpost',
            name='nlp_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facebookpost',
            name='scrape_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date scraped'),
        ),
        migrations.AlterField(
            model_name='facebookpost',
            name='time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date published'),
        ),
    ]
