# Generated by Django 3.1.4 on 2021-01-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0009_auto_20210103_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookpost',
            name='reactions',
            field=models.TextField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='facebookpost',
            name='image',
            field=models.URLField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='facebookpost',
            name='images',
            field=models.URLField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='facebookpost',
            name='link',
            field=models.URLField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='facebookpost',
            name='manual_description',
            field=models.TextField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='facebookpost',
            name='nlp_description',
            field=models.TextField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='facebookpost',
            name='post_text',
            field=models.TextField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='facebookpost',
            name='post_url',
            field=models.URLField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='facebookpost',
            name='text',
            field=models.TextField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='facebookpost',
            name='video',
            field=models.URLField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='facebookpost',
            name='video_thumbnail',
            field=models.URLField(blank=True, max_length=900, null=True),
        ),
    ]
