# Generated by Django 3.1.4 on 2021-01-06 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0010_auto_20210106_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookpost',
            name='w3_fb_url',
            field=models.URLField(blank=True, max_length=900, null=True),
        ),
    ]
