# Generated by Django 3.1.4 on 2021-01-08 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0012_facebookpost_fetched_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookpost',
            name='anger',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facebookpost',
            name='haha',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facebookpost',
            name='like',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facebookpost',
            name='love',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facebookpost',
            name='sorry',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facebookpost',
            name='wow',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
