# Generated by Django 3.1.4 on 2021-01-10 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0013_auto_20210108_2243'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Website',
        ),
    ]
